### ISSUE TITLE
what should the saml request look like?

### ISSUE THREAD

**Issue by bosskovic** [PracticallyGreen/omniauth-saml#65]
Hi, I have hit some problems trying to set up the gem, and I guess that I am missing something, but I am not sure what exactly. Please advise.

I have configured the gem with these parameters that I received from the idp:

```yaml
    issuer: 'my app name'
    assertion_consumer_service_url: my_callback_url
    idp_sso_target_url: https://idpprovider/SLO.saml2
    idp_cert: "-----BEGIN CERTIFICATE-----\nMIIEET ... Yfte7A==\n-----END CERTIFICATE-----"
    name_identifier_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'
```

When I send a request to the idp, it looks like this:

```xml
<samlp:AuthnRequest AssertionConsumerServiceURL="http://my_callback_url"
                    Destination="https://idpprovider/SLO.saml2"
                    ID="_c564cad0-774f-0133-8254-02199c956c29"
                    IssueInstant="2015-11-27T16:13:51Z"
                    Version="2.0"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    >
    <saml:Issuer>My app name</saml:Issuer>
    <samlp:NameIDPolicy AllowCreate="true"
                        Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
                        />
</samlp:AuthnRequest>
```

and the response is: **500 Server Error**. 
Am I doing something wrong? 
Is the certificate supposed to be a part of the request (because it is missing from the request)? 
Should the certificate be specified the way I do it?

Do I need to serve a metadata file from my app?
